### ISSUE TITLE
Owner and Maintenance

### ISSUE THREAD

**Issue by Dignifiedquire** [share/ShareJS#371]
Hey everyone,

I've been using sharejs for some time now, and I've seen that the maintenance and issue answering is not the greatest at the moment. @josephg seems to have stopped working on this pretty much right now, and I only see @nateps pushing some updates. For that reason I wanted to ask what the plans are for the future and if you plan on working more on it in the future. 
As I probably use sharejs for the foreseeable future and already need to maintain a [fork](https://github.com/codio/sharejs) I wanted to ask if you might want some help, as I'd rather try and keep the main repos up to date then to maintain independent and ever more diverging forks.

//cc @josephg @nateps @nornagon

**Comment by nateps** [comment]
Thanks for bringing up the question. @josephg and I are going to sync up about it this week, and I'll send an update.

**Comment by Dignifiedquire** [comment]
@nateps on that conversation?

**Comment by jpgilchrist** [comment]
bump.

**Comment by dbryand** [comment]
Also curious about this.

**Comment by hatpick** [comment]
@dbryand Check Joseph post here: https://groups.google.com/forum/#!forum/sharejs

**Comment by pedrosanta** [comment]
@Dignifiedquire:
> try and keep the main repos up to date then to maintain independent and ever more diverging forks.

Exactly. I agree, as I'll also be using ShareJS for a project for a while and be able to collaborate somehow. So the easier we can make to maintain, develop and move forward ShareJS (by far the most developed OT library out there) the better.

**Comment by nateps** [comment]
Hey all, thanks for the interest, and Joseph's post was indeed the outcome of our discussion. Joseph is going to own completing a new version of ShareJS that is single server only and a basic implementation to get a realtime editor up and running quickly. I'll be running with ShareDB, which will be a variant that will share as much as possible (particularly the same OT types), and it will essentially be the merging of what is currently LiveDB + ShareJS 0.7. I'm currently spending a good amount of time on ShareDB making it more scalable and efficient. Joseph is working on the new JSON OT type that is going to be a huge step forward. Going to close this issue, since it is resolved now.

**Comment by cypha** [comment]
So Devon Govett's suggestion of keeping everything modular is a no-go? I was really hoping to keep all components modular as well.

**Comment by nateps** [comment]
Modularity and sharing code is always a goal. We will share code where it makes sense and as much as reasonable without impacting the clarity and maintainability of the code.

**Comment by pedrosanta** [comment]
@nateps seems like a good roadmap. Sharing the OT types and the modular goal it's wise.

**Comment by pedrosanta** [comment]
Just another note. As ShareJS, OT and Derby gains momentum, I think it would be wise to continue the effort to keep the communication going between all stakeholders - when presenting and discussing ideas, roadmaps, API's, etc. :+1:
